---
# tasks file for instalar-docker
- name: Eliminar paquetes conflictivos
  apt: 
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes  # Elimina también archivos de configuración
    autoremove: yes  # Limpia dependencias innecesarias

- name: Actualizar lista de paquetes
  apt:
    update_cache: yes # apt update


- name: Instalar dependencias necesarias
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Crear directorios para keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  
- name: Descargar clave GPG de Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/aptkeyrings/docker.asc

- name: Agregar repositorio oficial de Docker
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    mode: '0644'

- name: Actualizar lista de paquetes después de agregar el repositorio
  apt:
    update_cache: yes

- name: Instalar ultima version
  apt:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Crear grupo "docker"
  group:
    name: docker
    state: present


- name: Agregar usuario al grupo "docker"
  user:
  name: "{{ ansible_user_id }}"
  groups: docker
  append: yes