---
# tasks file for instalar-docker
- name: Eliminar paquetes conflictivos
  apt: 
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes  # Elimina también archivos de configuración
    autoremove: yes  # Limpia dependencias innecesarias

- name: Actualizar lista de paquetes
  apt:
    update_cache: yes # apt update


- name: Instalar dependencias necesarias
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Crear directorios para keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  
## Hay q ver como corregir esto, porque cuando lo volves a ejecutar se queda esperando a que el responda ssi queres sobrescribrir el archivo
- name: Añadir Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg

- name: Añadir repositorio de Docker
  shell: echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Actualizar lista de paquetes después de agregar el repositorio
  apt:
    update_cache: yes

- name: Instalar ultima version
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    
- name: Crear grupo "docker"
  group:
    name: docker
    state: present


- name: Agregar usuario al grupo "docker"
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes